### ISSUE TITLE
Oi

### ISSUE THREAD

**Issue by d-nery** [ThundeRatz/UART_PPM#1]
Olar, esse repositorio ainda é necessário? Hahah

~sdd rolê temporário~

@erickotsuka @FelipeGdM @freitas-renato

**Comment by freitas-renato** [comment]
Não sei se o repo é necessário, mas acho bom ter esse programa em algum lugar. ~~onde?~~

**Comment by FelipeGdM** [comment]
Arquiva o repo

**Comment by d-nery** [comment]
É que tipo, tem literalmente um arquivo hahaha
Acho que não precisa ter mesmo, se tudo der certo não vamos mais usar e esse arquivo pode ficar no drive mesmo caso seja necessário num futuro distante
O objetivo inicial era que o código da TPM Trekking viesse pra cá, mas ela já tem o próprio repositório agora

**Comment by tiagoshibata** [comment]
Só arquiva (código em drive não :sob: )

**Comment by d-nery** [comment]
dkfugsyid é um arquivo soooo haha fica feio
Inclusive alguém apaga esses com ~ ou dá nomes decentes pra eles plmdds se for pra arquivar, e coloca um readme qualquer

**Comment by tiagoshibata** [comment]
Farei

**Comment by tiagoshibata** [comment]
Posso arquivar já?

**Comment by d-nery** [comment]
Ué, já tinha visto arquivado hahaha, pode

**Comment by tiagoshibata** [comment]
Eu voltei pra ver se alguém queria falar mais algo hahaha. Beleza então
